# Generated by Django 3.2.5 on 2021-12-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Username', max_length=30)),
                ('question_1', models.BooleanField(help_text='Do you have a caffeine addiction')),
            ],
        ),
    ]
