# Generated by Django 3.2.5 on 2022-01-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20220113_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='links',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='template',
            field=models.TextField(default='base_article'),
        ),
    ]
