# Generated by Django 3.2.5 on 2022-01-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
