# Generated by Django 3.2.5 on 2022-01-24 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_article_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='questionary_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='questions',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.questionsmodel'),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='user_id',
            field=models.ForeignKey(db_column='questions', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
