# Generated by Django 3.2.5 on 2022-01-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20220124_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsmodel',
            name='question_1',
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='gender',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='job',
            field=models.CharField(default=12, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='questionary_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
