# Generated by Django 3.2.5 on 2022-01-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_questionsmodel_symptoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsmodel',
            old_name='user_id',
            new_name='user_questionary_id',
        ),
    ]
