# Generated by Django 3.2.5 on 2022-01-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_rename_user_id_questionsmodel_user_questionary_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='questions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='questions', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.questionsmodel'),
        ),
    ]
